export enum Icon {
    youtube = 'youtube',
    facebook = 'facebook',
    instagram = 'instagram',
    whatsapp = 'whatsapp',
    pdf = 'pdf',
    excel = 'excel',
    csv = 'csv',
    edit = 'edit',
    trash = 'trash',
    wasteGenerator = 'wasteGenerator',
    dropOffSpot = 'dropOffSpot',
    collector = 'collector',
    industry = 'industry',
}
